const wackySentences = [
    'Tickle a shark',
    'Jump on marshmallow trampoline',
    'Swim in chocolate pudding pool',
    'Ride unicycle on tightrope',
    'Dance battle with robot',
    'Paint masterpiece using spaghetti brush',
    'Compete in synchronized sneezing contest',
    'Play hide-and-seek with chameleon',
    'Build sandcastle on cloud',
    'Walk tightrope juggling flaming swords',
    'Spin in tornado of cotton candy',
    'Surf on pizza slice across cheese wave',
    'Run marathon on stilts',
    'Eat spaghetti with chopsticks in wind tunnel',
    'Ride roller coaster made of bubble wrap',
    'Play tennis with watermelon ball',
    'Dance tango with penguin',
    'Sing karaoke with talking parrots',
    'Sleep in rainbow-colored licorice hammock',
    'Slide down rainbow into pot of gold',
    'Hula hoop with flaming hoop',
    'Perform magic trick for squirrels',
    'Juggle water balloons filled with glitter',
    'Balance spoon on nose for day',
    'Skip rope with snake',
    'Play chess with chocolate chessboard',
    'Ride unicycle while hula hooping',
    'Eat pizza with glow-in-the-dark toppings',
    'Play drums using coconuts',
    'Have picnic in cotton candy field',
    'Slide down giant ice cream cone',
    'Dance Macarena underwater',
    'Walk tightrope blindfolded',
    'Wear hat made of living plants',
    'Perform stand-up comedy for penguins',
    'Jump into jelly-filled pool',
    'Do handstand on moving train',
    'Ride bicycle with square wheels',
    'Roller skate in grocery store',
    'Play soccer with balloon',
    'Make sand sculpture of dinosaur',
    'Have tea party with teddy bears',
    'Paint mural using feet',
    'Have pillow fight with clouds',
    'Balance spoon on nose while unicycling',
    'Hula hoop while eating popsicle',
    'Perform backflip on trampoline',
    'Play guitar with toes',
    'Dive into giant bowl of spaghetti',
    'Jump off banana-shaped diving board',
    'Spin on merry-go-round all day',
    'Ride skateboard down roller coaster',
    'Play ping pong with watermelon',
    'Dance salsa with flamingo',
    'Paint face like tiger and roar',
    'Skip rocks across frozen lake',
    'Juggle with chainsaws',
    'Eat hot dog with jelly',
    'Walk tightrope wearing roller skates',
    'Ride skateboard juggling flaming torches',
    'Dance with group of fireflies',
    'Fly kite in hurricane',
    'Perform somersault on trampoline',
    'Have picnic in sunflower field',
    'Slide down rainbow on sled',
    'Walk on stilts made of spaghetti',
    'Eat ice cream with fork',
    'Ride bike underwater',
    'Play volleyball with helium beach ball',
    'Paint portrait using elbows',
    'Balance spoon on nose while pogo sticking',
    'Hula hoop with giant donut',
    'Perform cartwheel on tightrope',
    'Ride unicycle while eating watermelon',
    'Dance waltz with walrus',
    'Sing karaoke with howling wolves',
    'Sleep in bubble gum hammock',
    'Slide down whipped cream-covered slide',
    'Juggle with bowling balls',
    'Wear hat made of balloons',
    'Perform magic trick for squirrels',
    'Jump rope with snake',
    'Fly to moon on broomstick',
    'Ride spaghetti rollercoaster',
    'Swim with top-hat dolphins',
    'Spy on squirrels invisibly',
    'Pillow fight with friendly ghost',
    'Visit candy land with unicorns',
    'Become bubble gum blower',
    'Dance in rain with penguin',
    'Solve mystery with team cats',
    'Build sandcastle on rainbow',
    'Play hide-and-seek with chameleon',
    'Tea party with Mad Hatter',
    'Become bubble wrap popper',
    'Explore city with mermaids',
    'Talk with wise old owl',
    'Marshmallow roaster extraordinaire',
    'Perform magic for alien audience',
    'Giant bubble for comfy living',
    'Train giraffe for circus'
]

export default wackySentences
