const wackySentences = [
    'dance with giraffes',
    'fly on marshmallow clouds',
    'bake cosmic sprinkle cakes',
    'surf chocolate waves',
    'play chess with talking mushrooms',
    'paint neon skies',
    'race snails in a marathon',
    'roller skate on rainbows',
    'have a picnic with friendly aliens',
    'sing to moonbeams',
    'jump on bubblegum trampolines',
    'fetch with robotic dogs',
    'build sandcastles in clouds',
    'explore underwater cities with mermaids',
    'solve jellybean crossword puzzles',
    'balance on spaghetti tightropes',
    'climb cotton candy mountains',
    'compose symphonies with rubber ducks',
    'converse with wise owls',
    'bungee jump from hot air balloons',
    'ride licorice bicycles',
    'stroll through candy cane forests',
    'write novels on banana peels',
    'handstand on rainbows',
    'sculpt with bubble wrap',
    'host tea parties for invisible friends',
    'sail pirate ships of cheese',
    'perform comedy routines for robots',
    'run laughter-powered marathons',
    'swim with jellyfish',
    'juggle flaming torches on tightropes',
    'ski down whipped cream mountains',
    "solve Rubik's Cubes on roller coasters",
    'karaoke with parrots',
    'build sandcastles in deserts',
    'take selfies with friendly dinosaurs',
    'race snails in slow motion',
    'dance on rainbow bridges',
    'play hide-and-seek with invisible friends',
    'sculpt sand dinosaurs',
    'play basketball with talking vegetables',
    'navigate chocolate bar mazes',
    'have thumb wars with friendly aliens',
    'rollerblade on giant pretzels',
    'play tag with fireflies',
    'construct towers of cards in windstorms',
    'solve emoji crossword puzzles',
    'have pillow fights with marshmallow pillows',
    'create art with spaghetti noodles',
    'ride roller coasters through candy jungles',
    'race turtles in slow motion',
    'perform ballet on tightropes',
    'build sandcastles on clouds',
    'paint portraits of talking flowers',
    'play soccer with teams of robots',
    'go on bike rides with penguins',
    'sail on chocolate rivers',
    'compose songs with musical vegetables',
    'engage in staring contests with statues',
    'take selfies with friendly robots',
    'play frisbee with talking dolphins',
    'create sculptures with recycled materials',
    'have picnics in fields of sunflowers',
    'play piano with my feet',
    'climb jellybean staircases',
    'engage in water balloon fights with acrobats',
    'build treehouses in bubblegum trees',
    'solve crossword puzzles with animal sounds',
    'balance spoons on noses',
    'ride roller coasters through tunnels of confetti',
    'race turtles in slow motion',
    'dance on rainbow bridges',
    'play hide-and-seek with invisible friends',
    'sculpt sand dinosaurs',
    'play basketball with talking vegetables',
    'navigate chocolate bar mazes',
    'have thumb wars with friendly aliens',
    'rollerblade on giant pretzels',
    'play tag with fireflies',
    'construct towers of cards in windstorms',
    'solve emoji crossword puzzles',
    'have pillow fights with marshmallow pillows',
    'create art with spaghetti noodles',
    'ride roller coasters through candy jungles',
    'race turtles in slow motion',
    'perform ballet on tightropes',
    'build sandcastles on clouds',
    'paint portraits of talking flowers',
    'play soccer with teams of robots',
    'go on bike rides with penguins',
    'sail on chocolate rivers',
    'compose songs with musical vegetables',
    'engage in staring contests with statues',
    'take selfies with friendly robots',
    'play frisbee with talking dolphins',
    'create sculptures with recycled materials',
    'have picnics in fields of sunflowers',
    'play piano with my feet',
    'climb jellybean staircases',
    'engage in water balloon fights with acrobats'
]

export default wackySentences
